import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeComponent from '~/@core/themes/ThemeComponent';
import StyledComponentsRegistry from '~/@core/themes/themeRegistry';
// import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ThemeComponent>{children}</ThemeComponent>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
